ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'VIDEO_FILE';
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'GOOGLE_DRIVE';
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'DROPBOX';
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'ONEDRIVE';
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'ZIP';
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'IMAGE';
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'INTERNAL_UPLOAD';
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'ATTACHMENT';
